### ISSUE TITLE
.NET building block not rendering correctly

### ISSUE THREAD

**Issue by marklewin** [Nexmo/nexmo-developer#1180]
## Description

I'm trying to create a new YML building block for the "Send an SMS" example.

## What did you expect to happen?

I expected the lines of code that I specified in the building block to render in the output.

## What actually happened?

It's showing the wrong lines of code and treating `System.Web.Mvc.HttpGet` as a label:
![screen shot 2018-10-29 at 18 25 23](https://user-images.githubusercontent.com/18176755/47671899-85c3f200-dba8-11e8-8833-b97dd002120a.png)

## Steps to reproduce:

Use this YML file:

```yml
---
title: .NET
language: dotnet
dependencies:
    - Nexmo.Csharp.Client
client:
    source: .repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Authentication/BasicAuth.cs
    from_line: 13
    to_line: 17
code:
    source: .repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs
    from_line: 38
    to_line: 43
run_command: 'Run using your IDE'
file_name: SMSController.cs
unindent: true 
```
