### ISSUE TITLE
Update Search Result Highlighting when Using Tab

### ISSUE THREAD

**Issue by cr0wst** [Nexmo/nexmo-developer#1485]
## Description

When using tab to select search result entries the highlighting isn't very obvious.

![image](https://user-images.githubusercontent.com/8314724/53425064-5ab0aa00-39b2-11e9-9427-28bf1b91dca3.png)

In this example I have used the tab key to highlight "Is completed call request sent to my webhook for every call?"

This can be changed via the `:focus` selector on `a.Nxd-search__result__link`:

```css
a.Nxd-search__result__link:focus {
    background-color: rgba(0,0,0,.1);
}
```
